name: build & deploy

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Install and Build
      run: |
        npm install
        npm run build
        
    - name: Deploy Build Files
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} 
      run: |
        cd vuepress/docs/src/.vuepress/dist
        git config --global user.email "swpiens@gmail.com"
        git config --global user.name "swpiens"
        git init
        git add -A
        git commit -m 'deploy with vuepress'
        git push -f https://${ACCESS_TOKEN}@github.com/${GITHUB_REPOSITORY}.git master:gh-pages
