name: build & deploy

on:
  push:
    branches: [ master ]

jobs:
   build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: testthedocs/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.MY_FIRST_SECRET }}
        BUILD_DIR: vuepress/docs/src/.vuepress/dist # The folder, the action should deploy.
        BUILD_SCRIPT: npm install && vuepress build vuepress/docs/src # The build script the action should run prior to deploying.
